### PR TITLE
Replaced deprecated 'compile' with 'api' and 'implementation'.

### PR DESCRIPTION
**Pull request by lingocoder**
## Description
Replaced java plugin with java-library plugin in fineract-provider/build.gradle. Replaced compile configuration with api and implementation in fineract-provider/dependencies.gradle and fineract-provider/dev-dependencies.gradle

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
@lingocoder would you like to raise this against https://github.com/apache/fineract/pulls instead of here?

**Comment by lingocoder** [comment]
Hey there,

Sure. Will do. And I will reference it to the FINERACT-777 ticket you mentioned in your Gradle forum post. Is there a particular branch you need the pull request to refer to?

Also just as a heads-up: I came across [*an openjpa-gradle-plugin issue*](http://bit.ly/RadCrtzNhnc) on my machine when I ran *`gradle check`* as the very first command after cloning the project for the first time. 

That plugin's *`:enhance`* task depends on a JDK 11-incompatable version of a particular module. A default version of that module is hard-coded into the plugin. The plugin does expose [*an extension that is meant to provide a way to override the default*](http://bit.ly/RadCrtzMeta) with a user-specified version. But when used with JDK 11, the extension itself throws a different exception.

I worked around the *`:enhance`* issue by excluding that task from the build with: *`gradle -x enhance check`*.

You can find more details [*in the openjpa-gradle-plugin ticket*](http://bit.ly/RadCrtz8) I raised yesterday.

**Comment by vorburger** [comment]
> Is there a particular branch you need the pull request to refer to?

Raise all Finerat PRs against the `develop` branch.

But I suspect that the Gradle upgrade from https://github.com/apache/fineract/pull/525 (see [FINERACT-700](https://issues.apache.org/jira/browse/FINERACT-700)) will be a hard pre-requisite requirement for being able to do this? You would certainly be very welcome to first help us to wrap that one up... :smile: 

> Also just as a heads-up: I came across [_an openjpa-gradle-plugin issue_](http://bit.ly/RadCrtzNhnc) on my machine when I ran _`gradle check`_ as the very first command after cloning the project for the first time.
> 
> That plugin's _`:enhance`_ task depends on a JDK 11-incompatable version of a particular module. 

FYI there are a number of different problems re. Java 11 - on that front, you are can help over on https://github.com/apache/fineract/pull/609.

> You can find more details [_in the openjpa-gradle-plugin ticket_](http://bit.ly/RadCrtz8) I raised yesterday.

I'll watch that. FYI I didn't seem to run into that problem, last time I tried this.

**Comment by vorburger** [comment]
==> https://issues.apache.org/jira/browse/FINERACT-777

**Pull request closed without merging**
